[package]
name = "infrs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["http1"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tower-http = { version = "0.5", features = ["trace"] }
candle-core = { version = "0.3", default-features = false }
candle-nn = { version = "0.3", default-features = false }
candle-transformers = { version = "0.3", default-features = false }
tokenizers = "0.15"
hf-hub = "0.3"
clap = { version = "4.4", features = ["derive"] }
config = "0.13"
uuid = { version = "1.6", features = ["v4"] }
chrono = "0.4"
