name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg cpu_only"  # Default to CPU-only builds

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Check clippy
        run: cargo clippy -- -D warnings
      
      - name: Run tests
        run: cargo test

  build-cpu:
    name: Build (CPU)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --verbose

  build-cuda:
    name: Build (CUDA)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""  # Clear CPU-only flag
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.1.0'
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --verbose 