name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # CPU builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: fastllm-cpu-linux
            cuda: false
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: fastllm-cpu-macos
            cuda: false
          # CUDA build (Linux only)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: fastllm-cuda-linux
            cuda: true

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install CUDA
        if: matrix.cuda
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.1.0'
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Set CPU-only flag
        if: "!matrix.cuda"
        run: echo "RUSTFLAGS=--cfg cpu_only" >> $GITHUB_ENV
      
      - name: Build Release
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/fastllm artifacts/${{ matrix.artifact_name }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/${{ matrix.artifact_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 